"""Added tasks table

Revision ID: 1934c2ec8b3d
Revises: 
Create Date: 2023-05-03 18:14:16.608129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1934c2ec8b3d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('dueDate', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task')
    # ### end Alembic commands ###
